# Generated by Django 5.2.8 on 2025-12-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='sale',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='selling_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
